# Generated by Django 3.1.3 on 2020-11-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'blank': 'Cant be empty'}, max_length=250, verbose_name="doctor's first name")),
                ('second_name', models.CharField(error_messages={'blank': 'Cant be empty'}, max_length=250, verbose_name="doctor's second name")),
                ('bio', models.TextField(verbose_name="doctor's biography")),
                ('diploma', models.ImageField(upload_to='', verbose_name="doctor's diplomas")),
                ('avatar', models.ImageField(upload_to='', verbose_name="doctor's photo")),
                ('rating', models.IntegerField(verbose_name="doctor's rating")),
                ('date_of_registration', models.DateTimeField(auto_now=True, verbose_name="doctor's date of registration")),
                ('profession', models.CharField(choices=[('Rehabilitator', 'Physiotherapist'), ('Masseur', 'Trainer')], default='instructor', max_length=13, verbose_name="doctor's specialization")),
            ],
            options={
                'ordering': ('-rating',),
            },
        ),
    ]
