# Generated by Django 3.1.3 on 2020-11-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name="doctor's rating"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profession',
            field=models.CharField(choices=[('Rehab', 'Rehabilitator'), ('Physio', 'Physiotherapist'), ('Mass', 'Masseur'), ('Train', 'Trainer')], default='instructor', max_length=13, verbose_name="doctor's specialization"),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('photo', models.URLField(verbose_name='Link for photo for your post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
