# Generated by Django 3.1.3 on 2020-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctor_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='User name'),
            preserve_default=False,
        ),
    ]
