# Generated by Django 3.1.3 on 2020-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20201127_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('PT', 'Personal training'), ('GT', 'Group training'), ('MS', 'Massage'), ('RT', 'Rehabilitation training')], default='training', max_length=21, verbose_name="doctor's profession"),
        ),
    ]
