# Generated by Django 3.1.3 on 2020-11-27 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of registration'),
        ),
    ]
